# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlxgen < Formula
  desc "tool to generate sqlx models from schemas and queries"
  homepage "https://github.com/mvoorberg/sqlxgen"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.4/sqlxgen_Darwin_arm64.tar.gz"
      sha256 "77e0faa43e23a1ea1d1ee1f0a0d308a9c3c5dba8fdd177e908040d80b7df8bf9"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.4/sqlxgen_Darwin_x86_64.tar.gz"
      sha256 "3b24d23a07ec784b538feac60b51b7eddbe0f141b11fe276d2ef6dd59cf34561"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.4/sqlxgen_Linux_arm64.tar.gz"
      sha256 "6e753c4c69a95c50bb5e959e8d1299d6df5e267aa6a62b38b1ca83a5c3c4ce6c"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.4/sqlxgen_Linux_x86_64.tar.gz"
      sha256 "8e8275b6d04bacd6464426b87f1213a7ea7e57e512b0151894004bd5e16083cb"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  test do
    system "#{bin}/sqlxgen version"
  end
end
