# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlxgen < Formula
  desc "tool to generate sqlx models from schemas and queries"
  homepage "https://github.com/mvoorberg/sqlxgen"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.6/sqlxgen_Darwin_arm64.tar.gz"
      sha256 "4350bd1a0dbb2bfe09f1081eea2f5f1163141dc2c987e60515ac323484a539b3"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.6/sqlxgen_Darwin_x86_64.tar.gz"
      sha256 "573ce44612549652e19acd8add0c05c235b00bb3cc2cdb8774e4a7f73c35cd7f"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.6/sqlxgen_Linux_arm64.tar.gz"
      sha256 "7bcc20890c01ce2f4eeed7c65e91863f75c74c2e90ee6640c9e6e92a4cb0ae0b"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvoorberg/sqlxgen/releases/download/v1.0.6/sqlxgen_Linux_x86_64.tar.gz"
      sha256 "6943b5629ade49e827ac8095d1c04218a03b798a8cf62c3b95349059156d3027"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  test do
    system "#{bin}/sqlxgen version"
  end
end
